// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrknxtullpqldaxmetdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFya254dHVsbHBxbGRheG1ldGR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDM0MjksImV4cCI6MjA3MzYxOTQyOX0.jDUU3zHin6wyWH3T7Uweima7npZxWS08Hk-ycJ3uQYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});